name: Deploy Next.js app to ECR
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  deploy: 
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./client
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials from IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/temp-nextjs-test-ecr-deploy-iam-role-${{secrets.AWS_REGION}}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: temp-nextjs-test-app
          IMAGE_TAG: latest
        run: | 
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
